services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # MongoDB siempre expuesto en el puerto 27017
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - ./init/mongo:/docker-entrypoint-initdb.d
    networks:
      - finapp-network

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"  # Puerto fijo para MySQL
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./init/mysql:/docker-entrypoint-initdb.d
    networks:
      - finapp-network

  app:
    build: .
    container_name: finapp-backend
    ports:
      - "3000:3000"  # Puerto fijo para la aplicación
    environment:
      - PORT=3000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - finapp-network
    depends_on:
      - mongodb
      - mysql

networks:
  finapp-network:
    driver: bridge
